### ISSUE TITLE
unable to run from itch.io

### ISSUE THREAD

**Issue by GeorgeWL** [tesselode/mika-micro#1]
:rotating_light: tool [Cynthia Micro](https://tesselode.itch.io/cynthia-micro) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/3e76d26053588879f903bb0b3eb2a202).

:running: I tried running it cause wanted to try it out, but immediately recieved the error of "unabe to find executable" and then the app didn't run.

**Comment by tesselode** [comment]
cynthia micro isn't a standalone program, but a plugin that you run in vst hosts, such as a daw like ableton live or fl studio. sorry if that's confusing! i actually could make standalone builds, but i'm not sure how useful that would be
