### ISSUE TITLE
cynthia doesn't work in FL Stuido 32bit ,But works well in 64bit .

### ISSUE THREAD

**Issue by 2439905184** [tesselode/mika-micro#2]
Could you fix the bug ,I don't have the ability to fix it.

**Comment by tesselode** [comment]
what do you mean by "doesn't work?" no audio? freeze?

**Comment by torridgristle** [comment]
32bit version of Cynthia Micro working in FL Studio 32bit + Win7 64bit here, Using Version 6 according to the Itch.io download description, the version uploaded January ~23rd.  No apparent issues.
